# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!
from view import dragWidget
from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(851, 531)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(832, 531))
        MainWindow.setSizeIncrement(QtCore.QSize(0, -4609))
        MainWindow.setBaseSize(QtCore.QSize(500, 500))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mainFrame = QtWidgets.QFrame(self.centralWidget)
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.leftCol = QtWidgets.QFrame(self.mainFrame)
        self.leftCol.setGeometry(QtCore.QRect(-10, -10, 511, 491))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftCol.sizePolicy().hasHeightForWidth())
        self.leftCol.setSizePolicy(sizePolicy)
        self.leftCol.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftCol.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftCol.setObjectName("leftCol")
#        self.pushButton = QtWidgets.QPushButton(self.leftCol)
#        self.pushButton.setGeometry(QtCore.QRect(190, 100, 121, 81))
#        self.pushButton.setObjectName("pushButton")
#        self.pushButton_2 = QtWidgets.QPushButton(self.leftCol)
#        self.pushButton_2.setGeometry(QtCore.QRect(190, 30, 113, 32))
#        self.pushButton_2.setObjectName("pushButton_2")
#        self.pushButton_3 = QtWidgets.QPushButton(self.leftCol)
#        self.pushButton_3.setGeometry(QtCore.QRect(190, 410, 113, 32))
#        self.pushButton_3.setObjectName("pushButton_3")
        self.rightCol = QtWidgets.QFrame(self.mainFrame)
        self.rightCol.setGeometry(QtCore.QRect(500, 0, 321, 451))
        self.rightCol.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rightCol.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightCol.setObjectName("rightCol")
        self.topRight = QtWidgets.QFrame(self.rightCol)
        self.topRight.setGeometry(QtCore.QRect(0, 0, 311, 231))
        self.topRight.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topRight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topRight.setObjectName("topRight")
        self.worldItemsLabel = QtWidgets.QLabel(self.topRight)
        self.worldItemsLabel.setGeometry(QtCore.QRect(0, 0, 331, 20))
        self.worldItemsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.worldItemsLabel.setObjectName("worldItemsLabel")
        self.worldItemsList = QtWidgets.QScrollArea(self.topRight)
        self.worldItemsList.setGeometry(QtCore.QRect(0, 20, 331, 211))
        self.worldItemsList.setWidgetResizable(True)
        self.worldItemsList.setObjectName("worldItemsList")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 329, 209))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeWidget = QtWidgets.QTreeWidget(self.scrollAreaWidgetContents_2)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.verticalLayout.addWidget(self.treeWidget)
        self.worldItemsList.setWidget(self.scrollAreaWidgetContents_2)
        self.bottomRight = QtWidgets.QFrame(self.rightCol)
        self.bottomRight.setGeometry(QtCore.QRect(0, 230, 321, 221))
        self.bottomRight.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottomRight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomRight.setObjectName("bottomRight")
        self.tasksLabel = QtWidgets.QLabel(self.bottomRight)
        self.tasksLabel.setGeometry(QtCore.QRect(0, 0, 331, 16))
        self.tasksLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tasksLabel.setObjectName("tasksLabel")
        self.tasksList = dragWidget.DragWidget(self.bottomRight)
        #self.tasksList = QtWidgets.QScrollArea(self.bottomRight)
        self.tasksList.setGeometry(QtCore.QRect(0, 20, 331, 241))
        self.tasksList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tasksList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tasksList.setWidgetResizable(True)
        self.tasksList.setObjectName("tasksList")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 313, 223))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.tasksList.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.mainFrame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 851, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuWindow = QtWidgets.QMenu(self.menuBar)
        self.menuWindow.setObjectName("menuWindow")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionState_Browser = QtWidgets.QAction(MainWindow)
        self.actionState_Browser.setCheckable(True)
        self.actionState_Browser.setEnabled(True)
        self.actionState_Browser.setObjectName("actionState_Browser")
        self.actionPlanner = QtWidgets.QAction(MainWindow)
        self.actionPlanner.setCheckable(True)
        self.actionPlanner.setChecked(True)
        self.actionPlanner.setObjectName("actionPlanner")
        self.actionEditor = QtWidgets.QAction(MainWindow)
        self.actionEditor.setCheckable(True)
        self.actionEditor.setObjectName("actionEditor")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionClose)
        self.menuWindow.addAction(self.actionPlanner)
        self.menuWindow.addAction(self.actionState_Browser)
        self.menuWindow.addAction(self.actionEditor)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuWindow.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
#        self.pushButton.setText(_translate("MainWindow", "Task A"))
#        self.pushButton_2.setText(_translate("MainWindow", "InitialState"))
#        self.pushButton_3.setText(_translate("MainWindow", "Goal State"))
        self.worldItemsLabel.setText(_translate("MainWindow", "World Items"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Blocks"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "Cubes"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "1"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "2"))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "3"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "Pyramids"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "A"))
        self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "B"))
        self.treeWidget.topLevelItem(1).child(2).setText(0, _translate("MainWindow", "C"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.tasksLabel.setText(_translate("MainWindow", "Tasks"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuWindow.setTitle(_translate("MainWindow", "Window"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As..."))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionState_Browser.setText(_translate("MainWindow", "State Browser"))
        self.actionPlanner.setText(_translate("MainWindow", "Planner"))
        self.actionEditor.setText(_translate("MainWindow", "Editor"))
