# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(842, 531)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(832, 531))
        MainWindow.setSizeIncrement(QtCore.QSize(0, -4609))
        MainWindow.setBaseSize(QtCore.QSize(500, 500))
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mainFrame = QtWidgets.QFrame(self.centralWidget)
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.leftCol = QtWidgets.QFrame(self.mainFrame)
        self.leftCol.setGeometry(QtCore.QRect(0, 0, 501, 451))
        self.leftCol.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.leftCol.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftCol.setObjectName("leftCol")
        self.initialState = QtWidgets.QPushButton(self.leftCol)
        self.initialState.setGeometry(QtCore.QRect(160, 30, 113, 32))
        self.initialState.setObjectName("initialState")
        self.goalState = QtWidgets.QPushButton(self.leftCol)
        self.goalState.setGeometry(QtCore.QRect(180, 410, 113, 32))
        self.goalState.setObjectName("goalState")
        self.rightCol = QtWidgets.QFrame(self.mainFrame)
        self.rightCol.setGeometry(QtCore.QRect(500, 0, 321, 451))
        self.rightCol.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rightCol.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightCol.setObjectName("rightCol")
        self.topRight = QtWidgets.QFrame(self.rightCol)
        self.topRight.setGeometry(QtCore.QRect(0, 0, 311, 231))
        self.topRight.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topRight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topRight.setObjectName("topRight")
        self.worldItemsLabel = QtWidgets.QLabel(self.topRight)
        self.worldItemsLabel.setGeometry(QtCore.QRect(0, 0, 331, 20))
        self.worldItemsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.worldItemsLabel.setObjectName("worldItemsLabel")
        self.worldItemsList = QtWidgets.QScrollArea(self.topRight)
        self.worldItemsList.setGeometry(QtCore.QRect(0, 20, 331, 211))
        self.worldItemsList.setWidgetResizable(True)
        self.worldItemsList.setObjectName("worldItemsList")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 329, 209))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.treeWidget = QtWidgets.QTreeWidget(self.scrollAreaWidgetContents_2)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.verticalLayout.addWidget(self.treeWidget)
        self.worldItemsList.setWidget(self.scrollAreaWidgetContents_2)
        self.bottomRight = QtWidgets.QFrame(self.rightCol)
        self.bottomRight.setGeometry(QtCore.QRect(0, 230, 321, 221))
        self.bottomRight.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottomRight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomRight.setObjectName("bottomRight")
        self.tasksLabel = QtWidgets.QLabel(self.bottomRight)
        self.tasksLabel.setGeometry(QtCore.QRect(0, 0, 331, 16))
        self.tasksLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tasksLabel.setObjectName("tasksLabel")
        self.tasksList = QtWidgets.QScrollArea(self.bottomRight)
        self.tasksList.setGeometry(QtCore.QRect(0, 20, 331, 241))
        self.tasksList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tasksList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tasksList.setWidgetResizable(True)
        self.tasksList.setObjectName("tasksList")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 329, 322))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setContentsMargins(15, 15, 15, 15)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.task5 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.task5.setMinimumSize(QtCore.QSize(100, 100))
        self.task5.setObjectName("task5")
        self.gridLayout.addWidget(self.task5, 2, 1, 1, 1)
        self.task0 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.task0.setMinimumSize(QtCore.QSize(100, 100))
        self.task0.setObjectName("task0")
        self.gridLayout.addWidget(self.task0, 0, 0, 1, 1)
        self.task1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.task1.setMinimumSize(QtCore.QSize(100, 100))
        self.task1.setObjectName("task1")
        self.gridLayout.addWidget(self.task1, 0, 1, 1, 1)
        self.task2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.task2.setMinimumSize(QtCore.QSize(100, 100))
        self.task2.setObjectName("task2")
        self.gridLayout.addWidget(self.task2, 1, 0, 1, 1)
        self.task4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.task4.setMinimumSize(QtCore.QSize(100, 100))
        self.task4.setObjectName("task4")
        self.gridLayout.addWidget(self.task4, 2, 0, 1, 1)
        self.task3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.task3.setMinimumSize(QtCore.QSize(100, 100))
        self.task3.setObjectName("task3")
        self.gridLayout.addWidget(self.task3, 1, 1, 1, 1)
        self.tasksList.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.mainFrame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 842, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionClose)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.initialState.setText(_translate("MainWindow", "Initial State"))
        self.goalState.setText(_translate("MainWindow", "Goal State"))
        self.worldItemsLabel.setText(_translate("MainWindow", "World Items"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Blocks"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "Cubes"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "1"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "2"))
        self.treeWidget.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "3"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "Pyramids"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "A"))
        self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "B"))
        self.treeWidget.topLevelItem(1).child(2).setText(0, _translate("MainWindow", "C"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.tasksLabel.setText(_translate("MainWindow", "Tasks"))
        self.task5.setText(_translate("MainWindow", "Task F"))
        self.task0.setText(_translate("MainWindow", "Task A"))
        self.task1.setText(_translate("MainWindow", "Task B"))
        self.task2.setText(_translate("MainWindow", "Task C"))
        self.task4.setText(_translate("MainWindow", "Task E"))
        self.task3.setText(_translate("MainWindow", "Task D"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As..."))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))

